2gis/nuclear-river

Environments/Templates/quartz.Test.Russia.config
Environments/quartz.Production.Russia.config

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/2gis/nuclear-river/4)

quartz.config schedule changed

---

CustomerIntelligence/Tests/CustomerIntelligence.Replication.DataTest.Model/CustomerIntelligence.Replication.StateInitialization.Tests.csproj
CustomerIntelligence/Tests/CustomerIntelligence.Replication.DataTest.Model/packages.config
build/build.csproj
build/datatest.ps1
build/metadata.psm1
build/packages.config

ping @maximpashuk @denisivan0v 
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/2gis/nuclear-river/25)

Добавил вывод результатов datatest в формате nunit 2.5

---

CustomerIntelligence/CustomerIntelligence.Domain/Specifications/Specs.Map.Facts.CI.cs
CustomerIntelligence/Tests/CustomerIntelligence.Replication.DataTest.Model/CustomerIntelligence.Replication.StateInitialization.Tests.csproj
CustomerIntelligence/Tests/CustomerIntelligence.Replication.DataTest.Model/TestCaseMetadataSource.CategoryGroup.cs
CustomerIntelligence/Tests/CustomerIntelligence.Replication.DataTest.Model/TestCaseMetadataSource.Client.cs
CustomerIntelligence/Tests/CustomerIntelligence.Replication.DataTest.Model/TestCaseMetadataSource.Firm.cs
CustomerIntelligence/Tests/CustomerIntelligence.Replication.DataTest.Model/TestCaseMetadataSource.IgnoredEntities.cs
CustomerIntelligence/Tests/CustomerIntelligence.Replication.DataTest.Model/TestCaseMetadataSource.Project.cs
CustomerIntelligence/Tests/CustomerIntelligence.Replication.DataTest.Model/TestCaseMetadataSource.Territory.cs

closes #9
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/2gis/nuclear-river/28)

data tests for CI context

---

CustomerIntelligence/CustomerIntelligence.Domain/Specifications/Specs.Map.CI.Statistics.cs
CustomerIntelligence/Tests/CustomerIntelligence.Replication.Tests/StatisticsTransformation/StatisticsFinalTransformationTests.cs

[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/2gis/nuclear-river/37)

Fixed statistics replication

---

Environments/Erm.Business.Russia.config
Environments/Erm.Edu.Czech.config
Environments/Erm.Edu.Russia.config
Environments/Erm.Production.Czech.config
Environments/Erm.Production.Russia.config

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Review on Reviewable"/>](https://reviewable.io/reviews/2gis/nuclear-river/46)

Corporate bus support for Czech

---

CustomerIntelligence/CustomerIntelligence.OperationsProcessing/CustomerIntelligence.OperationsProcessing.csproj
CustomerIntelligence/CustomerIntelligence.OperationsProcessing/Identities/Operations/ActualizeOrderAggregatedIndicatorsPersistedCacheIdentity.cs
CustomerIntelligence/CustomerIntelligence.OperationsProcessing/Identities/Operations/ActualizeOrderPlatformIdentity.cs
CustomerIntelligence/CustomerIntelligence.OperationsProcessing/Identities/Operations/AssignClientRelatedActivitiesIdentity.cs
CustomerIntelligence/CustomerIntelligence.OperationsProcessing/Identities/Operations/ChangeOrderReleaseCountIdentity.cs
CustomerIntelligence/CustomerIntelligence.OperationsProcessing/Identities/Operations/DetachFirmFromClientIdentity.cs
CustomerIntelligence/CustomerIntelligence.OperationsProcessing/Identities/Operations/DisqualifyClientIdentity.cs
CustomerIntelligence/CustomerIntelligence.OperationsProcessing/Identities/Operations/DisqualifyFirmIdentity.cs
CustomerIntelligence/CustomerIntelligence.OperationsProcessing/Identities/Operations/OperationIdentityIds.cs
CustomerIntelligence/CustomerIntelligence.OperationsProcessing/Identities/Operations/QualifyClientIdentity.cs
CustomerIntelligence/CustomerIntelligence.OperationsProcessing/Identities/Operations/QualifyFirmIdentity.cs
CustomerIntelligence/CustomerIntelligence.OperationsProcessing/OperationRegistryMetadataSource.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/2gis/nuclear-river/48)

актуализация реестра операций

---

CustomerIntelligence/CustomerIntelligence.OperationsProcessing/CustomerIntelligence.OperationsProcessing.csproj
CustomerIntelligence/CustomerIntelligence.OperationsProcessing/packages.config
CustomerIntelligence/CustomerIntelligence.Querying.Host/CustomerIntelligence.Querying.Host.csproj
CustomerIntelligence/CustomerIntelligence.Querying.Host/packages.config
CustomerIntelligence/Tests/CustomerIntelligence.OperationsProcessing.Tests/CustomerIntelligence.OperationsProcessing.Tests.csproj
CustomerIntelligence/Tests/CustomerIntelligence.OperationsProcessing.Tests/packages.config
CustomerIntelligence/Tests/CustomerIntelligence.Replication.Tests/CustomerIntelligence.Replication.Tests.csproj
CustomerIntelligence/Tests/CustomerIntelligence.Replication.Tests/packages.config
Querying/Querying.Http/Querying.Http.csproj
Querying/Querying.Http/packages.config
Querying/Querying.Storage/Querying.Storage.csproj
Querying/Querying.Storage/packages.config
Replication/Replication.Core/Replication.Core.csproj
Replication/Replication.Core/packages.config
Replication/Replication.EntryPoint/Replication.EntryPoint.csproj
Replication/Replication.EntryPoint/packages.config
Replication/Replication.OperationsProcessing/Replication.OperationsProcessing.csproj
Replication/Replication.OperationsProcessing/packages.config

Иван одобрил pull request с tracing
@rechkalov @denisivan0v
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/2gis/nuclear-river/62)

tracing stable version

---

CustomerIntelligence/CustomerIntelligence.Querying.Host/Web.config
Environments/ConvertUseCases.Business.MultiCulture.config
Environments/ConvertUseCases.Edu.MultiCulture.config
Environments/ConvertUseCases.Production.MultiCulture.config
Environments/Erm.Business.Russia.config
Environments/Erm.Edu.Czech.config
Environments/Erm.Edu.Russia.config
Environments/Erm.Production.Czech.config
Environments/Erm.Production.Russia.config
Environments/Templates/ConvertUseCases.Test.MultiCulture.config
Environments/Templates/Erm.Test.Czech.config
Environments/Templates/Erm.Test.Russia.config
Replication/Replication.EntryPoint/App.config

@denisivan0v
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/2gis/nuclear-river/64)

Updated logstash logging uri

---

Environments/Erm.Production.Czech.config
Environments/Erm.Production.Russia.config

https://jira.2gis.ru/browse/ERM-9106
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/2gis/nuclear-river/65)

Modified integration bus connection string

---

Environments/quartz.Production.MultiCulture.config
Environments/quartz.Production.Russia.config

Это увеличение размера пакета хорошо себя показало за последние сутки на среде Production.Russia.
Если в будущем появятся таймауты - откатим.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/2gis/nuclear-river/68)

Increase batch size

---

CustomerIntelligence/CustomerIntelligence.OperationsProcessing/Primary/ImportFactsFromErmHandler.cs

@denisivan0v 
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/2gis/nuclear-river/69)

Added logging of TUCs that lead to huge amount of commands

---

CustomerIntelligence/Tests/CustomerIntelligence.Replication.Tests/Transformation/FactDependencyTests.Activity.cs
CustomerIntelligence/Tests/CustomerIntelligence.Replication.Tests/Transformation/FactDependencyTests.CategoryFirmAddress.cs
CustomerIntelligence/Tests/CustomerIntelligence.Replication.Tests/Transformation/FactDependencyTests.CategoryGroup.cs
CustomerIntelligence/Tests/CustomerIntelligence.Replication.Tests/Transformation/FactDependencyTests.CategoryOrganizationUnit.cs
CustomerIntelligence/Tests/CustomerIntelligence.Replication.Tests/Transformation/FactDependencyTests.Contact.cs
CustomerIntelligence/Tests/CustomerIntelligence.Replication.Tests/Transformation/FactDependencyTests.Data.cs
CustomerIntelligence/Tests/CustomerIntelligence.Replication.Tests/Transformation/FactDependencyTests.FirmAddress.cs
CustomerIntelligence/Tests/CustomerIntelligence.Replication.Tests/Transformation/FactDependencyTests.cs
Replication/Replication.Core/FactChangesDetector.cs
Replication/Replication.Core/Facts/FactProcessor.cs
Replication/Replication.Core/Replication.Core.csproj
Replication/Replication.EntryPoint/Factories/Replication/UnityFactProcessorFactory.cs

update вызывается только на те факты,
в которых изменилось хотя бы одно поле.
соответственно, не изменившиеся факты не создают событий
@denisivan0v @maximpashuk
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/2gis/nuclear-river/70)

Optimized fact recalculatoin

---

build/metadata.ps1
build/updateschemas.ps1

Пофиксил проблему со схемой Transport. Добавил её в метаданные, немного изменил сами метаданные.
Проверил на 21 тестовой среде, схемы пересоздались нормально.
@rechkalov @denisivan0v
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/2gis/nuclear-river/81)

Support schema transport

---

CustomerIntelligence/CustomerIntelligence.Replication/Accessors/ProjectAccessor.cs
CustomerIntelligence/Tests/CustomerIntelligence.Replication.Tests/Actors/SyncDataObjectsActorTests.Project.cs

@denisivan0v
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/2gis/nuclear-river/88)

Фикс для Украины после переименования Днепропетровска в Днепр.

---

Replication/Replication.Core/Actors/CreateDataObjectsActor.cs
Replication/Replication.Core/Actors/DeleteDataObjectsActor.cs
Replication/Replication.Core/Actors/EntityActorBase.cs
Replication/Replication.Core/Actors/SyncDataObjectsActor.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/2gis/nuclear-river/93)

Added possibility to set data changes handler in EntityActorBase

---

StateInitialization/StateInitialization.Core/BulkReplicationActor.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/2gis/nuclear-river/95)

Replaced parallel replication with serial one

---

CustomerIntelligence/CustomerIntelligence.Replication/Actors/ProjectStatisticsAggregateRootActor.cs
CustomerIntelligence/CustomerIntelligence.Replication/Specifications/Specs.Find.CI.cs

Сообщение на пересчёт всего проекта приводило к исключению
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/2gis/nuclear-river/100)

Fixed statistics flow processing

---

Replication/Replication.Core/Actors/ReplaceDataObjectsActor.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/2gis/nuclear-river/102)

Fixed another statistics flow processing bug

---

Environments/Erm.Production.config
Environments/Erm.config
Environments/Templates/Erm.Test.config

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/2gis/nuclear-river/107)

Fixed config transformations

---

StateInitialization/StateInitialization.Core/Actors/ReplaceDataObjectsInBulkActor.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/2gis/nuclear-river/108)

Add statisctics update after migrating data

---

Environments/quartz.Production.Russia.config

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/2gis/nuclear-river/110)

Уменьшил размер пакета ImportAggregatesFlow

---

CustomerIntelligence/CustomerIntelligence.OperationsProcessing/Final/ProjectStatisticsAggregateCommandsHandler.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/2gis/nuclear-river/113)

Fixed statistics delay reporting

---

CustomerIntelligence/CustomerIntelligence.OperationsProcessing/Primary/ImportFactsFromBitHandler.cs
CustomerIntelligence/CustomerIntelligence.OperationsProcessing/Primary/ImportFactsFromErmHandler.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/2gis/nuclear-river/114)

Fixed BIT messages processing

---

StateInitialization/StateInitialization.Core/Actors/GlobalLocker.cs
StateInitialization/StateInitialization.Core/Actors/IndexesManagementActor.cs
StateInitialization/StateInitialization.Core/StateInitialization.Core.csproj

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/2gis/nuclear-river/133)

threads sync on dealing with indexes

---

StateInitialization/StateInitialization.Core/Actors/BulkReplicationActor.cs
StateInitialization/StateInitialization.Core/Actors/ConstraintsManagementActor.cs
StateInitialization/StateInitialization.Core/Actors/DisableIndexesActor.cs
StateInitialization/StateInitialization.Core/Actors/EnableIndexesActor.cs
StateInitialization/StateInitialization.Core/Actors/IndexManager.cs
StateInitialization/StateInitialization.Core/Actors/TruncateTableActor.cs
StateInitialization/StateInitialization.Core/Actors/UpdateTableStatisticsActor.cs
StateInitialization/StateInitialization.Core/Commands/DisableIndexesCommand.cs
StateInitialization/StateInitialization.Core/Commands/EnableIndexesCommand.cs
StateInitialization/StateInitialization.Core/Commands/TruncateTableCommand.cs
StateInitialization/StateInitialization.Core/Commands/UpdateTableStatisticsCommand.cs
StateInitialization/StateInitialization.Core/Factories/ReplaceDataObjectsInBulkActorFactory.cs
StateInitialization/StateInitialization.Core/StateInitialization.Core.csproj
StateInitialization/StateInitialization.Core/Storage/Table.cs
StateInitialization/StateInitialization.Core/Storage/TableName.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/2gis/nuclear-river/136)

fix bulk replication when multiple entities replicate in one table

---

Hosting/Hosting.Interactive/Properties/AssemblyInfo.cs
Querying/Querying.Edm/EdmModelBuilder.cs
Querying/Querying.Edm/Emit/EmitHelper.cs
Querying/Querying.Http/Controllers/GenericODataController.cs
Querying/Querying.Http/Emit/DynamicControllersRegistrar.cs
Querying/Querying.Metadata/Builders/EntityElementBuilder.cs
Querying/Querying.Metadata/Builders/EntityRelationElementBuilder.cs
Querying/Querying.Metadata/Builders/StructuralModelElementBuilder.cs
Querying/Querying.Metadata/Elements/BaseMetadataElement.cs
Querying/Querying.Metadata/Elements/EntityPropertyElement.cs
Querying/Querying.Metadata/Elements/PrimitiveTypeElement.cs
Querying/Querying.Metadata/Elements/StructuralModelElement.cs
Querying/Querying.Metadata/Features/EntityIdentityFeature.cs
Querying/Querying.Metadata/Features/EntitySetFeature.cs
Querying/Querying.Metadata/Properties/AssemblyInfo.cs
StateInitialization/StateInitialization.Core/Actors/CreateTableCopyActor.cs
StateInitialization/StateInitialization.Core/Actors/IndexManager.cs

fix StyleCop warnings
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/2gis/nuclear-river/141)

fix index shadow copy

---

Replication/Replication.Core/EqualityComparerFactory.cs
Replication/Tests/Replication.Core.Tests/EqualityComparerFactoryTests.cs

Добавил возможность использовать сторонние IEqualityComparer для сравнения полей.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/2gis/nuclear-river/142)

Доработал EqualityComparerFactory

---

StateInitialization/StateInitialization.Core/Actors/BulkInsertDataObjectsActor.cs
StateInitialization/StateInitialization.Core/Actors/BulkReplicationActor.cs
StateInitialization/StateInitialization.Core/Actors/CopyTablesActor.cs
StateInitialization/StateInitialization.Core/Actors/CreateTableCopyActor.cs
StateInitialization/StateInitialization.Core/Actors/IndexManager.cs
StateInitialization/StateInitialization.Core/Actors/ReplaceTableActor.cs
StateInitialization/StateInitialization.Core/Commands/BulkInsertDataObjectsCommand.cs
StateInitialization/StateInitialization.Core/Commands/CreateTableCopyCommand.cs
StateInitialization/StateInitialization.Core/StateInitialization.Core.csproj

Для создания постоянной копии таблиц.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/2gis/nuclear-river/143)

Добавил CopyTablesActor

---

StateInitialization/StateInitialization.Core/Actors/ReplaceTableActor.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/2gis/nuclear-river/146)

correct dropping of extended property on index

---

Replication/Replication.Core/Actors/CreateDataObjectsActor.cs
Replication/Replication.Core/Actors/DeleteDataObjectsActor.cs
Replication/Replication.Core/Actors/SyncDataObjectsActor.cs
Replication/Replication.Core/Actors/ValueObjectActor.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/2gis/nuclear-river/147)

Добавил проверки на пустоту коллекций

---

StateInitialization/StateInitialization.Core/SqlConnectionExtensions.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/2gis/nuclear-river/148)

Remove statements timeout for SMO

---

Replication/Replication.Core/EqualityComparerFactory.cs

Если значение свойства "null", то вызываться GetHashCode не должен,
даже если для этого свойства IEqualityComparer реализован вручную.
Ибо в документации сказано, что GetHashCode должен кидать исключение,
если ему передать "null".
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/2gis/nuclear-river/150)

Исправил ошибку в EqualityComparerFactory
